name: feedify
description: "**Feedify** is a smart food app that connects users with local restaurants, food vendors, and home chefs.   It offers quick and easy food ordering with personalized meal recommendations.   Enjoy real-time delivery tracking and exclusive deals.   Discover diverse cuisines and share dining experiences with the community.   **Feedify** makes every meal convenient, fresh, and delicious!"


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  image_picker:
  firebase_core: ^3.12.1
  firebase_analytics:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  dio:
  logger:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/home/
