// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQzXzJn7gBjhbU9g0ld-ckzcgWtv-p-I',
    appId: '1:842691558760:web:9ecde5fff4ba8639822add',
    messagingSenderId: '842691558760',
    projectId: 'feedify-e4e20',
    authDomain: 'feedify-e4e20.firebaseapp.com',
    databaseURL: 'https://feedify-e4e20-default-rtdb.firebaseio.com',
    storageBucket: 'feedify-e4e20.firebasestorage.app',
    measurementId: 'G-FJBH5VJMLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMw9U9AnoY2_juMI-7EdLrirpnduBTn_k',
    appId: '1:842691558760:android:712ac9ed164d72ba822add',
    messagingSenderId: '842691558760',
    projectId: 'feedify-e4e20',
    databaseURL: 'https://feedify-e4e20-default-rtdb.firebaseio.com',
    storageBucket: 'feedify-e4e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0_j9CnrzDsQO2-Ep9h9_kvCMitQOKms',
    appId: '1:842691558760:ios:a606e40eb04b45b5822add',
    messagingSenderId: '842691558760',
    projectId: 'feedify-e4e20',
    databaseURL: 'https://feedify-e4e20-default-rtdb.firebaseio.com',
    storageBucket: 'feedify-e4e20.firebasestorage.app',
    iosBundleId: 'com.master.feedify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0_j9CnrzDsQO2-Ep9h9_kvCMitQOKms',
    appId: '1:842691558760:ios:a606e40eb04b45b5822add',
    messagingSenderId: '842691558760',
    projectId: 'feedify-e4e20',
    databaseURL: 'https://feedify-e4e20-default-rtdb.firebaseio.com',
    storageBucket: 'feedify-e4e20.firebasestorage.app',
    iosBundleId: 'com.master.feedify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiQzXzJn7gBjhbU9g0ld-ckzcgWtv-p-I',
    appId: '1:842691558760:web:bddc069f3e600ddd822add',
    messagingSenderId: '842691558760',
    projectId: 'feedify-e4e20',
    authDomain: 'feedify-e4e20.firebaseapp.com',
    databaseURL: 'https://feedify-e4e20-default-rtdb.firebaseio.com',
    storageBucket: 'feedify-e4e20.firebasestorage.app',
    measurementId: 'G-L4C1WTNMV6',
  );

}