// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7DsedrqqcNNaaInLimHkuTNmS7dpM7Yc',
    appId: '1:331317022062:web:8844e831dbbe72e255057f',
    messagingSenderId: '331317022062',
    projectId: 'feedify-43813',
    authDomain: 'feedify-43813.firebaseapp.com',
    storageBucket: 'feedify-43813.firebasestorage.app',
    measurementId: 'G-FELTF4KP3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQASWim6-KYa9Newl3GMgRs_ScrYfdOQ',
    appId: '1:331317022062:android:7823c13e5e3eb03f55057f',
    messagingSenderId: '331317022062',
    projectId: 'feedify-43813',
    storageBucket: 'feedify-43813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi5P2QJSsXZc4nuSQvadj7v9ALhcCBSPA',
    appId: '1:331317022062:ios:c7b531f05de97e1755057f',
    messagingSenderId: '331317022062',
    projectId: 'feedify-43813',
    storageBucket: 'feedify-43813.firebasestorage.app',
    iosBundleId: 'com.master.feedify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi5P2QJSsXZc4nuSQvadj7v9ALhcCBSPA',
    appId: '1:331317022062:ios:c7b531f05de97e1755057f',
    messagingSenderId: '331317022062',
    projectId: 'feedify-43813',
    storageBucket: 'feedify-43813.firebasestorage.app',
    iosBundleId: 'com.master.feedify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7DsedrqqcNNaaInLimHkuTNmS7dpM7Yc',
    appId: '1:331317022062:web:1b509fe879f9fa9d55057f',
    messagingSenderId: '331317022062',
    projectId: 'feedify-43813',
    authDomain: 'feedify-43813.firebaseapp.com',
    storageBucket: 'feedify-43813.firebasestorage.app',
    measurementId: 'G-NSZMRHQF5Y',
  );

}